### ISSUE TITLE
Framework choice

### ISSUE THREAD

**Issue by dennisdegreef** [LonelyPullRequestsHQ/lonelypullrequests.com#1]
What framework do we want to use? And can be bootstrap it quickly? @fvdb

**Comment by fvdb** [comment]
I feel most comfortable with Symfony, but it's not that important to me. We can start with the domain anyway. Perhaps just focus on the domain first and have a simple CLI for adding PRs and seeing whether the importing actually works. Then later we can build an API and a JS client to do it in the browser.

**Comment by dennisdegreef** [comment]
We can do that, but I think we can better yet just choose for Symfony in that case. Since we can create those implementations the right way directly then, instead of prototyping it first in some CLI scripts.

If there would be a basic symfony setup, I can go nuts and implement a few usecases.
Must be me, but for Symfony, I always wonder how to bootstrap such a project. Just `composer require symfony/symfony` ? Or do you need to create the directory structure yourself? You could copy a complete hello world tutorial thingy, but that would leave some mess. This has always been unclear to me with symfony.

**Comment by fvdb** [comment]
There are instructions here: http://symfony.com/doc/current/best_practices/creating-the-project.html

Or if you'd like, I can set up the basic structure and create a PR for it.

**Comment by dennisdegreef** [comment]
Let's see who's faster :) I'm off to FOSDEM this weekend, so I can't say for sure if i have time for this.
But thanks for the link!

**Comment by dennisdegreef** [comment]
I setup the basics, configured travis-ci and phpunit structure, and made you a project collaborator.
If you could review this lonely PR, and merge it if ack'ed, that would be awesome! :D
