### ISSUE TITLE
Setup twitterbot on new PR

### ISSUE THREAD

**Issue by dennisdegreef** [LonelyPullRequestsHQ/lonelypullrequests.com#5]
Whenever a new PR is registered, a tweet should be send out

**Comment by dennisdegreef** [comment]
Any recommendations for a composer package to implement tweeting?

**Comment by fruitl00p** [comment]
Why a composer package per se when it's already outthere as a microservice?
https://github.com/JavaScriptKC/github-tweet-pull-requests

**Comment by dennisdegreef** [comment]
This tweets out every comment that is made, instead of when a notification to our system's user is made. (from looking at it quickly)

**Comment by dennisdegreef** [comment]
Fixed in #29
